# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fdb780fb929cbcb8e15ea4e0645335d26c4c1ea6efbc35663693d2d817e0e0e22d65bb2e7b678646f6d18639d25d60a45a11b9a52c7f02a3e546fcd4de323af

test:
  secret_key_base: a9d0f98c9c635e208f2569faad2887c74510b5e884730f5a830c11c4a1c8029594e49314c002e20a6a332a168e8a4f715a90f7af21d11e4b257d9fc51697e5ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
